services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak-service
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 9090
    ports:
      - 9090:9090
    command:
      - "start-dev"
